# Generated by Django 3.2.6 on 2022-02-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('Personal', 'Personal'), ('School', 'School'), ('Business', 'Business'), ('Office', 'Office')], default='Personal', max_length=8)),
                ('title', models.CharField(max_length=50)),
                ('place', models.CharField(choices=[('City Proper', 'City Proper'), ('Jaro', 'Jaro'), ('La Paz', 'La Paz'), ('Lapuz', 'Lapuz'), ('Mandurriao', 'Mandurriao'), ('Molo', 'Molo'), ('Villa Arevalo', 'Villa Arevalo'), ('Lapuz', 'Lapuz')], default='City Proper', max_length=16)),
                ('note', models.TextField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
