# Generated by Django 3.2.6 on 2022-02-28 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20220228_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['-date_created']},
        ),
    ]
