# Generated by Django 3.2.6 on 2022-02-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_alter_tasks_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, unique=True),
        ),
    ]
