# Generated by Django 3.2.6 on 2022-02-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_alter_tasks_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
