# Generated by Django 3.2.6 on 2022-03-04 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0010_tasks_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={},
        ),
    ]
