# Generated by Django 3.2.6 on 2022-03-04 02:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0011_alter_tasks_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
